name: CI/CD Pipeline

on:
  push:
    branches:
      - main
env:
  IMAGE_REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ secrets.USERNAME_GITHUB }}
        password: ${{ secrets.PASSWORD_GITHUB }}

    - name: Build the Podman image
      run: |
        podman build . --tag ghcr.io/${{ secrets.USERNAME_GITHUB }}/wisecow:$(basename ${{ github.ref }}) -f Dockerfile
        podman push ghcr.io/${{ secrets.USERNAME_GITHUB }}/wisecow:$(basename ${{ github.ref }})

  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Kubeconfig
  #     uses: azure/setup-kubectl@v1
  #     with:
  #       version: 'v1.18.0'
  #   - name: Install kustomize
  #     run: |
  #       curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
  #       sudo mv kustomize /usr/local/bin/
  #   - name: Deploy to Kubernetes
  #     run: |
  #       kubectl apply -f k8s/
  #     env:
  #       KUBECONFIG: ${{ secrets.KUBECONFIG }}