name: CI/CD Pipeline

on:
  push:
    branches:
      - main
env:
  IMAGE_REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Kubeconfig
  #     uses: azure/setup-kubectl@v1
  #     with:
  #       version: 'v1.18.0'
  #   - name: Install kustomize
  #     run: |
  #       curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
  #       sudo mv kustomize /usr/local/bin/
  #   - name: Deploy to Kubernetes
  #     run: |
  #       kubectl apply -f k8s/
  #     env:
  #       KUBECONFIG: ${{ secrets.KUBECONFIG }}